version: '3.1'

services:

  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: spring_user
      MYSQL_PASSWORD: spring_pass
      MYSQL_ROOT_PASSWORD: my_secret
      MYSQL_DATABASE: db_test
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: spring_mq_user
      RABBITMQ_DEFAULT_PASS: spring_mq_pass
    ports:
      - "5672:5672"
      - "15672:15672"


volumes:
  db:
    driver: local